### PR TITLE
[WIP] Partial == and === ligature support

### PR DESCRIPTION
**Pull request by Baldrs**

### CODE REVIEW

**Comment by be5invis** [comment]
@Baldrs I am refactoring the ligation support of Iosevka, separated it into several files.

**Comment by alozytskyi** [comment]
@be5invis Ok I will update accordingly

**Comment by be5invis** [comment]
@Baldrs @alozytskyi 
I am going to release a 1.11.5 later today, and you can continue the work based on 1.11.5.
Cheers.

**Comment by Baldrs** [comment]
@be5invis oops, wrong account :-) Will update after you release

**Comment by Baldrs** [comment]
I currently don't have enough time to do this, so maybe somebody else can create them? If not I'll try again later, when I'll have more time/

**Pull request closed without merging**
