### PR TITLE
Draft: Add playing cards (`U+1F0A0`‥`U+1F0F5`) (#1835).

### PR DESCRIPTION
**Pull request by jmcwilliams403**
Marking as a draft because this execution both feels and looks kind of hacked together in its current state. I'd really like to improve it somehow.

The digits currently aren't tailored to fill the vertical real estate they have access to, so two-row cards still use the same inner height as enclosed alphanumerics, which is one inner cap-height character.

I did go ahead and make a non-descending `Q` glyph for Queen (along with the existing one for `J` for Jack), which looks more visually consistent with the rest of the ranks, and it would probably look even better if the inner text filled the vertical space more.

I also didn't know what to put on the playing card back character (if anything) so I made it an empty negative boxed character. Maybe it could potentially have some sort of ornamental design on the back, but that's up to you.

Regarding the inclusion of the Red Joker:

Believe it or not, the "red" joker here isn't the one that actually has a registered emoji form (the black joker is), but due to the unfortunate name, many non-emoji fonts tend to neglect the red joker and only support the black and white.

Here, I have created a vertical shaded star for the red joker based on the black and white example glyphs for colored geometric shapes shown in the Unicode charts.

```
🂠🂡🂢🂣🂤🂥🂦🂧🂨🂩🂪🂫🂬🂭🂮
 🂱🂲🂳🂴🂵🂶🂷🂸🂹🂺🂻🂼🂽🂾🂿
 🃁🃂🃃🃄🃅🃆🃇🃈🃉🃊🃋🃌🃍🃎🃏
 🃑🃒🃓🃔🃕🃖🃗🃘🃙🃚🃛🃜🃝🃞🃟
🃠🃡🃢🃣🃤🃥🃦🃧🃨🃩🃪🃫🃬🃭🃮🃯
🃰🃱🃲🃳🃴🃵
```
image

### CODE REVIEW

**Comment by be5invis** [comment]
Need to unify the thickness of the frame.

**Comment by jmcwilliams403** [comment]
Better playing card back:
image

**Comment by be5invis** [comment]
Later you could make the digits in the regular suites somehow taller

**Comment by jmcwilliams403** [comment]
Progress:
image

**Comment by be5invis** [comment]
You could make the letter and symbol slightly narrower for regular cards.

**Comment by jmcwilliams403** [comment]
image

**Pull request merged**
