### PR TITLE
Draft: Add variant selectors For Cyrillic Lower A/Ve.

### PR DESCRIPTION
**Pull request by jmcwilliams403**
#2427 was kind of foreshadowing what I wanted to do here.
```
ABC.DEF.GHI.JKL.MNO.PQRS.TUV.WXYZ
abc.def.ghi.jkl.mno.pqrs.tuv.wxyz
!iIlL17|¦ ¢coO08BbDQ $5SZ2zs 96µm
float il1[]={1-2/3.4,5+6=7/8%90};
1234567890 ,._-+= >< «¯-¬_» ~–÷+×
{*}[]()<>`+-=$/#_%^@\&|~?'" !,.;:
CG6Qg9q¶ äöü Þẞðþſß ΓΔΛαδιλμξπτχ∂
ЖЗКУЭЯавжзклмнруфчъыьэя  <= != ==
```
example of tall cursive form:

ss03 upright:
image
ss03 italic:
image

example of disunified upright single storey vs. double storey for latin vs. cyrillic:

ss07 upright:
image
ss07 italic:
image

example of where in the original font the latin characters have italic forms but the cyrillic characters do not:

ss09 upright:
image
ss09 italic:
image

example of where it might be more tasteful to use a toothed or tailed design for the cyrillic letter when the latin letter uses a toothless design:

ss12 upright:
image
ss12 italic:
image

example of a convention to use a particular motion-serifed design under slab when the original font doesn't use a cursive ve but the font as a whole still uses italics otherwise:

ss18 slab upright:
image
ss18 slab italic:
image

### CODE REVIEW

**Comment by be5invis** [comment]
SS03/italic is tall?

**Comment by be5invis** [comment]
For now just add VSes using VX. I will reorganize them at v31.

**Comment by jmcwilliams403** [comment]
> SS03/italic is tall?

yes, it's an example of tall cursive, based on Consolas:
image

> For now just add VSes using VX. I will reorganize them at v31.

That's what I did.

**Comment by be5invis** [comment]
That's fine. It is good enough to merge now.

**Pull request merged**
