### PR TITLE
Komi De, Komi Dje, Komi Sje

### PR DESCRIPTION
**Pull request by Logo121**
image

* Komi De in lowercase is same as d. In uppercase, it is said to be "like a turned P", but I implemented it as Latin De without the top bar instead (the resulting shape is the same, but it makes more sense semantically I guess?).
* For Komi Dje, the bowls have to be rounded and joined with the stem so that the hook shape wouldn't break the shape open.
For uppercase I just made a "Rounded Reverse Yeri" shape copying from the existing functions, and for lowercase I followed the db diagraph shape. This makes lowercase dje not have variants, but db has the same problem anyway.
* For Komi Sje, its shape is unfortunately(?) identical to some G variants. I just used that but following the hook depth convention of all other shapes (and configured to follow C instead).
  * As far as I'm aware, there are fonts implementing these Sje differently:
    * Some (most?) identify it with the usual G with inward hook (Noto Sans Mono, Arial, etc.)
    * Some keep the hook pointing upward, consistent with other Komi palatal characters (Roboto, Dejavu Sans, etc)
    * Andika goes as far as curling the hook inwards image
    * Some give the hook a crossbar (along with the other palatal characters) even though they are sanserif (Nishiki-teki, JuliaMono)
  * All of these forms (except Andika's one I presume) have some justification/evidence to it, and while these variants are definitely implementable (e.g. using variants of G), I'm leaving it as is (one unified, no-crossbar shape) for now. They are too niche to warrant a variant selector anyway I suppose

### CODE REVIEW

**Comment by Logo121** [comment]
I may be biased, but I do think most "original fonts" are sloppy in one way or another anyway, considering their concern was more to create a letter for those phonemes than designing a proper font for the alphabet.
image
While it may be true that some serif fonts (this one is from wiki) add a thick crossbar to the shape, they also tend to be even thicker than the horizontal strokes in the same font, which makes it questionable if it is intended as a crossbar either.

I also don't see what's wrong with those no-crossbar variants being display fonts; if anything that shows that a font with graphical design in mind would consider the crossbar not an integral part of the glyph, or at least that they are not *that* important and more of a stylistic decision. Some of those fonts in question aren't even *that* fancy-styled in the first place: 
image
(from [Unicode proposal](https://www.unicode.org/wg2/docs/n2224.pdf))

**Comment by Logo121** [comment]
I've also clicked through the book list [you supplied from that other discussion](https://github.com/kreativekorp/open-relay/issues/61) and I have come to the same conclusion:
* There are probably like 1 font for serif and 1 font for sanserif for text at that time anyway, with the sanserif font based on the serif version with that very chunky tail shape.
* But whenever a book decides to use their own (sanserif) font in the cover, the "chunk" or crossbar or whateverthing almost always gets removed or at least reduced.
I am probably biased on this, but I do tend toward's JapanYoshi's stance in that the fact that most text use that sanserif font isn't very conclusive of anything, so it's probably fine the way it is.

**Comment by chelovechishko** [comment]
To add to conversation: As you could see, 
Ульянов-Ленин - Молодцов exemplar contains the stroke.
Second one 
Букварь - кровать
 contains serif and sans-serif fonts and `ԏ` still contains the stroke (of course, possible that new ones letters got created only in one [serif] variant, so was used only they ¯\_(ツ)_/¯).
And in addition copy of part of alphabet 
Алфавит - ССЛльНнь

 (also some info about book publication 
1926 - тираж 6000 экз
 (6000 copies. Komi Publisher Press)
// books from webarchive of `foto11.com/komi/docs/molodtsovfont.htm`: shondiygor1926 and molodtsov1926.)

P. S. as for me, `ԋ` (and other ones) should be look alike `њ`, that is, `н` with 'ь', as the letter describes softness of the parential form  (dunno, does Molodtsov knows that there is already such a letter, in his town, where he worked at his times).
Just humble opinion.

**Comment by Logo121** [comment]
We're still doing this?

> contains serif and sans-serif fonts and `ԏ` still contains the stroke (of course, possible that new ones letters got created only in one [serif] variant, so was used only they ¯_(ツ)_/¯).

Yes, that is my conjecture (also JapanYoshi's in the other issue in FairfaxHD)

from https://wiki.komikyv.org/, we can also find several examples of the stroke absent:
[Ԋывпулӧн шувгӧм](https://wiki.komikyv.org/index.php/%D0%9D%D1%8C%D1%8B%D0%B2%D0%BF%D1%83%D0%BB%D3%A7%D0%BD_%D1%88%D1%83%D0%B2%D0%B3%D3%A7%D0%BC_(%D0%9C._%D0%9B%D0%B5%D0%B1%D0%B5%D0%B4%D0%B5%D0%B2%D0%BB%D3%A7%D0%BD_1929%CA%BC_%D0%B2%D0%BE%D1%81%D1%8F_%D0%BD%D0%B5%D0%B1%D3%A7%D0%B3))
image
[«Ыҗыд-виԍт» гіжӧԁыԍ ԍерпасторјас](https://wiki.komikyv.org/index.php/%C2%AB%D0%AB%D0%B4%D0%B6%D1%8B%D0%B4_%D0%B2%D0%B8%D1%81%D1%8C%D1%82%C2%BB_%D0%B3%D0%B8%D0%B6%D3%A7%D0%B4%D1%8B%D1%81%D1%8C_%D1%81%D0%B5%D1%80%D0%BF%D0%B0%D1%81%D1%82%D0%BE%D1%80%D1%8A%D1%8F%D1%81_(%D0%A2%D0%B8%D0%BC%D0%B0_%D0%92%D0%B5%D0%BD%D1%8C%D0%BB%D3%A7%D0%BD_1929%CA%BC_%D0%B2%D0%BE%D1%81%D1%8F_%D0%BD%D0%B5%D0%B1%D3%A7%D0%B3))
(note: this has both the "curled" sje and "hook" sje, contrasting with regular es.  
Other text on the cover uses the font with stroke)
image
[Знамеԋԋе : кујімторја ԏеш](https://wiki.komikyv.org/index.php/%D0%97%D0%BD%D0%B0%D0%BC%D0%B5%D0%BD%D0%BD%D1%8C%D3%A7_(%D0%9D%D1%91%D0%B1%D0%B4%D1%96%D0%BD%D1%81%D0%B0_%D0%92%D0%B8%D1%82%D1%82%D0%BE%D1%80%D0%BB%D3%A7%D0%BD_1930%CA%BC_%D0%B2%D0%BE%D1%81%D1%8F_%D0%BD%D0%B5%D0%B1%D3%A7%D0%B3)) (Author name only, the title is in cursive)
image
[Мыј лоӧ поԉіԏехнизм](https://wiki.komikyv.org/index.php/%D0%9C%D1%8B%D0%B9_%D0%BB%D0%BE%D3%A7_%D0%BF%D0%BE%D0%BB%D0%B8%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D0%B7%D0%BC_(1930%CA%BC_%D0%B2%D0%BE%D1%81%D1%8F_%D0%BD%D0%B5%D0%B1%D3%A7%D0%B3)) (heavily reduced hook)
image
[Моԉ](https://wiki.komikyv.org/index.php/%D0%9C%D0%BE%D0%BB%D1%8C_(%D0%9D%D1%91%D0%B1%D0%B4%D1%96%D0%BD%D1%81%D0%B0_%D0%92%D0%B8%D1%82%D1%82%D0%BE%D1%80%D0%BB%D3%A7%D0%BD_1931%CA%BC_%D0%B2%D0%BE%D1%81%D1%8F_%D0%BD%D0%B5%D0%B1%D3%A7%D0%B3))
image
[Ԅеԉԉа : 4 торја пјеса](https://wiki.komikyv.org/index.php/%D0%97%D0%B5%D0%BB%D0%BB%D1%8F_(%D0%9F%D0%B5%D0%B4%D1%8C_%D0%93%D0%B5%D0%BD%D1%8C%D0%BB%D3%A7%D0%BD_1931%CA%BC_%D0%B2%D0%BE%D1%81%D1%8F_%D0%BD%D0%B5%D0%B1%D3%A7%D0%B3))
image
[Проԉетарскӧј комі гіжыԍјас — сӧветјас ІX сјезԁлы](https://wiki.komikyv.org/index.php/%D0%9F%D1%80%D0%BE%D0%BB%D0%B5%D1%82%D0%B0%D1%80%D1%81%D0%BA%D3%A7%D0%B9_%D0%BA%D0%BE%D0%BC%D0%B8_%D0%B3%D0%B8%D0%B6%D1%8B%D1%81%D1%8C%D1%8F%D1%81_%E2%80%94_%D1%81%D3%A7%D0%B2%D0%B5%D1%82%D1%8A%D1%8F%D1%81_%D0%86X_%D1%81%D1%8A%D0%B5%D0%B7%D0%B4%D0%BB%D1%8B_(1931%CA%BC_%D0%B2%D0%BE%D1%81%D1%8F_%D0%BD%D0%B5%D0%B1%D3%A7%D0%B3)) (inner serif on sje but not lje, likely just for contrast with es)
image
[Кӧрымјӓс ԍілосујтӧм](https://wiki.komikyv.org/index.php/%D0%9A%D3%A7%D1%80%D1%8B%D0%BC%D1%8A%D1%8F%D1%81_%D1%81%D0%B8%D0%BB%D0%BE%D1%81%D1%83%D0%B9%D1%82%D3%A7%D0%BC_(1931%CA%BC_%D0%B2%D0%BE%D1%81%D1%8F_%D0%BD%D0%B5%D0%B1%D3%A7%D0%B3))
image
etc etc.

So in my opinion, it is definitely not *required* to have strokes for those characters.


> P. S. as for me, `ԋ` (and other ones) should be look alike `њ`, that is, `н` with 'ь', as the letter describes softness of the parential form (dunno, does Molodtsov knows that there is already such a letter, in his town, where he worked at his times).
> Just humble opinion.

[From the Unicode proposal](https://www.unicode.org/wg2/docs/n2224.pdf) it is explicitly mentioned that `ԋ` is not to be unified in shape with `њ`, because it **definitely** does not translate to other characters like `ԅԍԃ` or arguably `ԏ` (though te with bowl is in the Unicode pipeline and in use in Khanty dialects iirc)

**Pull request merged**
